/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KidWelcomeRouteImport } from './routes/kid.welcome'
import { Route as KidTreasuresRouteImport } from './routes/kid.treasures'
import { Route as KidTracksRouteImport } from './routes/kid.tracks'
import { Route as KidReadyRouteImport } from './routes/kid.ready'
import { Route as KidPracticeRouteImport } from './routes/kid.practice'
import { Route as KidMeRouteImport } from './routes/kid.me'
import { Route as KidHomeRouteImport } from './routes/kid.home'
import { Route as KidClassRouteImport } from './routes/kid.class'
import { Route as AdultSignInRouteImport } from './routes/adult.sign-in'
import { Route as AdultRecoverRouteImport } from './routes/adult.recover'
import { Route as AdultDashboardRouteImport } from './routes/adult.dashboard'
import { Route as AdultConsentRouteImport } from './routes/adult.consent'
import { Route as KidSetupThemeRouteImport } from './routes/kid.setup.theme'
import { Route as KidSetupNameRouteImport } from './routes/kid.setup.name'
import { Route as KidSetupGuideRouteImport } from './routes/kid.setup.guide'
import { Route as KidRewardRewardIdRouteImport } from './routes/kid.reward.$rewardId'
import { Route as KidModuleModuleIdRouteImport } from './routes/kid.module.$moduleId'
import { Route as KidLessonLessonIdRouteImport } from './routes/kid.lesson.$lessonId'
import { Route as KidCheckpointCheckpointIdRouteImport } from './routes/kid.checkpoint.$checkpointId'
import { Route as KidChapterChapterIdRouteImport } from './routes/kid.chapter.$chapterId'
import { Route as Char91__mockupChar93PreviewSplatRouteImport } from './routes/[__mockup].preview.$'
import { Route as Char91__componentChar93PreviewSplatRouteImport } from './routes/[__component].preview.$'
import { Route as KidTrackTrackIdMapRouteImport } from './routes/kid.track.$trackId.map'
import { Route as KidModuleModuleIdTestRouteImport } from './routes/kid.module.$moduleId.test'
import { Route as KidModuleModuleIdReviewRouteImport } from './routes/kid.module.$moduleId.review'
import { Route as KidModuleModuleIdResultRouteImport } from './routes/kid.module.$moduleId.result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KidWelcomeRoute = KidWelcomeRouteImport.update({
  id: '/kid/welcome',
  path: '/kid/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const KidTreasuresRoute = KidTreasuresRouteImport.update({
  id: '/kid/treasures',
  path: '/kid/treasures',
  getParentRoute: () => rootRouteImport,
} as any)
const KidTracksRoute = KidTracksRouteImport.update({
  id: '/kid/tracks',
  path: '/kid/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const KidReadyRoute = KidReadyRouteImport.update({
  id: '/kid/ready',
  path: '/kid/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const KidPracticeRoute = KidPracticeRouteImport.update({
  id: '/kid/practice',
  path: '/kid/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const KidMeRoute = KidMeRouteImport.update({
  id: '/kid/me',
  path: '/kid/me',
  getParentRoute: () => rootRouteImport,
} as any)
const KidHomeRoute = KidHomeRouteImport.update({
  id: '/kid/home',
  path: '/kid/home',
  getParentRoute: () => rootRouteImport,
} as any)
const KidClassRoute = KidClassRouteImport.update({
  id: '/kid/class',
  path: '/kid/class',
  getParentRoute: () => rootRouteImport,
} as any)
const AdultSignInRoute = AdultSignInRouteImport.update({
  id: '/adult/sign-in',
  path: '/adult/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdultRecoverRoute = AdultRecoverRouteImport.update({
  id: '/adult/recover',
  path: '/adult/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const AdultDashboardRoute = AdultDashboardRouteImport.update({
  id: '/adult/dashboard',
  path: '/adult/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdultConsentRoute = AdultConsentRouteImport.update({
  id: '/adult/consent',
  path: '/adult/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const KidSetupThemeRoute = KidSetupThemeRouteImport.update({
  id: '/kid/setup/theme',
  path: '/kid/setup/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const KidSetupNameRoute = KidSetupNameRouteImport.update({
  id: '/kid/setup/name',
  path: '/kid/setup/name',
  getParentRoute: () => rootRouteImport,
} as any)
const KidSetupGuideRoute = KidSetupGuideRouteImport.update({
  id: '/kid/setup/guide',
  path: '/kid/setup/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const KidRewardRewardIdRoute = KidRewardRewardIdRouteImport.update({
  id: '/kid/reward/$rewardId',
  path: '/kid/reward/$rewardId',
  getParentRoute: () => rootRouteImport,
} as any)
const KidModuleModuleIdRoute = KidModuleModuleIdRouteImport.update({
  id: '/kid/module/$moduleId',
  path: '/kid/module/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const KidLessonLessonIdRoute = KidLessonLessonIdRouteImport.update({
  id: '/kid/lesson/$lessonId',
  path: '/kid/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const KidCheckpointCheckpointIdRoute =
  KidCheckpointCheckpointIdRouteImport.update({
    id: '/kid/checkpoint/$checkpointId',
    path: '/kid/checkpoint/$checkpointId',
    getParentRoute: () => rootRouteImport,
  } as any)
const KidChapterChapterIdRoute = KidChapterChapterIdRouteImport.update({
  id: '/kid/chapter/$chapterId',
  path: '/kid/chapter/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91__mockupChar93PreviewSplatRoute =
  Char91__mockupChar93PreviewSplatRouteImport.update({
    id: '/__mockup/preview/$',
    path: '/__mockup/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91__componentChar93PreviewSplatRoute =
  Char91__componentChar93PreviewSplatRouteImport.update({
    id: '/__component/preview/$',
    path: '/__component/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const KidTrackTrackIdMapRoute = KidTrackTrackIdMapRouteImport.update({
  id: '/kid/track/$trackId/map',
  path: '/kid/track/$trackId/map',
  getParentRoute: () => rootRouteImport,
} as any)
const KidModuleModuleIdTestRoute = KidModuleModuleIdTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => KidModuleModuleIdRoute,
} as any)
const KidModuleModuleIdReviewRoute = KidModuleModuleIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => KidModuleModuleIdRoute,
} as any)
const KidModuleModuleIdResultRoute = KidModuleModuleIdResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => KidModuleModuleIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adult/consent': typeof AdultConsentRoute
  '/adult/dashboard': typeof AdultDashboardRoute
  '/adult/recover': typeof AdultRecoverRoute
  '/adult/sign-in': typeof AdultSignInRoute
  '/kid/class': typeof KidClassRoute
  '/kid/home': typeof KidHomeRoute
  '/kid/me': typeof KidMeRoute
  '/kid/practice': typeof KidPracticeRoute
  '/kid/ready': typeof KidReadyRoute
  '/kid/tracks': typeof KidTracksRoute
  '/kid/treasures': typeof KidTreasuresRoute
  '/kid/welcome': typeof KidWelcomeRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/kid/chapter/$chapterId': typeof KidChapterChapterIdRoute
  '/kid/checkpoint/$checkpointId': typeof KidCheckpointCheckpointIdRoute
  '/kid/lesson/$lessonId': typeof KidLessonLessonIdRoute
  '/kid/module/$moduleId': typeof KidModuleModuleIdRouteWithChildren
  '/kid/reward/$rewardId': typeof KidRewardRewardIdRoute
  '/kid/setup/guide': typeof KidSetupGuideRoute
  '/kid/setup/name': typeof KidSetupNameRoute
  '/kid/setup/theme': typeof KidSetupThemeRoute
  '/kid/module/$moduleId/result': typeof KidModuleModuleIdResultRoute
  '/kid/module/$moduleId/review': typeof KidModuleModuleIdReviewRoute
  '/kid/module/$moduleId/test': typeof KidModuleModuleIdTestRoute
  '/kid/track/$trackId/map': typeof KidTrackTrackIdMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adult/consent': typeof AdultConsentRoute
  '/adult/dashboard': typeof AdultDashboardRoute
  '/adult/recover': typeof AdultRecoverRoute
  '/adult/sign-in': typeof AdultSignInRoute
  '/kid/class': typeof KidClassRoute
  '/kid/home': typeof KidHomeRoute
  '/kid/me': typeof KidMeRoute
  '/kid/practice': typeof KidPracticeRoute
  '/kid/ready': typeof KidReadyRoute
  '/kid/tracks': typeof KidTracksRoute
  '/kid/treasures': typeof KidTreasuresRoute
  '/kid/welcome': typeof KidWelcomeRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/kid/chapter/$chapterId': typeof KidChapterChapterIdRoute
  '/kid/checkpoint/$checkpointId': typeof KidCheckpointCheckpointIdRoute
  '/kid/lesson/$lessonId': typeof KidLessonLessonIdRoute
  '/kid/module/$moduleId': typeof KidModuleModuleIdRouteWithChildren
  '/kid/reward/$rewardId': typeof KidRewardRewardIdRoute
  '/kid/setup/guide': typeof KidSetupGuideRoute
  '/kid/setup/name': typeof KidSetupNameRoute
  '/kid/setup/theme': typeof KidSetupThemeRoute
  '/kid/module/$moduleId/result': typeof KidModuleModuleIdResultRoute
  '/kid/module/$moduleId/review': typeof KidModuleModuleIdReviewRoute
  '/kid/module/$moduleId/test': typeof KidModuleModuleIdTestRoute
  '/kid/track/$trackId/map': typeof KidTrackTrackIdMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adult/consent': typeof AdultConsentRoute
  '/adult/dashboard': typeof AdultDashboardRoute
  '/adult/recover': typeof AdultRecoverRoute
  '/adult/sign-in': typeof AdultSignInRoute
  '/kid/class': typeof KidClassRoute
  '/kid/home': typeof KidHomeRoute
  '/kid/me': typeof KidMeRoute
  '/kid/practice': typeof KidPracticeRoute
  '/kid/ready': typeof KidReadyRoute
  '/kid/tracks': typeof KidTracksRoute
  '/kid/treasures': typeof KidTreasuresRoute
  '/kid/welcome': typeof KidWelcomeRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/kid/chapter/$chapterId': typeof KidChapterChapterIdRoute
  '/kid/checkpoint/$checkpointId': typeof KidCheckpointCheckpointIdRoute
  '/kid/lesson/$lessonId': typeof KidLessonLessonIdRoute
  '/kid/module/$moduleId': typeof KidModuleModuleIdRouteWithChildren
  '/kid/reward/$rewardId': typeof KidRewardRewardIdRoute
  '/kid/setup/guide': typeof KidSetupGuideRoute
  '/kid/setup/name': typeof KidSetupNameRoute
  '/kid/setup/theme': typeof KidSetupThemeRoute
  '/kid/module/$moduleId/result': typeof KidModuleModuleIdResultRoute
  '/kid/module/$moduleId/review': typeof KidModuleModuleIdReviewRoute
  '/kid/module/$moduleId/test': typeof KidModuleModuleIdTestRoute
  '/kid/track/$trackId/map': typeof KidTrackTrackIdMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adult/consent'
    | '/adult/dashboard'
    | '/adult/recover'
    | '/adult/sign-in'
    | '/kid/class'
    | '/kid/home'
    | '/kid/me'
    | '/kid/practice'
    | '/kid/ready'
    | '/kid/tracks'
    | '/kid/treasures'
    | '/kid/welcome'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/kid/chapter/$chapterId'
    | '/kid/checkpoint/$checkpointId'
    | '/kid/lesson/$lessonId'
    | '/kid/module/$moduleId'
    | '/kid/reward/$rewardId'
    | '/kid/setup/guide'
    | '/kid/setup/name'
    | '/kid/setup/theme'
    | '/kid/module/$moduleId/result'
    | '/kid/module/$moduleId/review'
    | '/kid/module/$moduleId/test'
    | '/kid/track/$trackId/map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adult/consent'
    | '/adult/dashboard'
    | '/adult/recover'
    | '/adult/sign-in'
    | '/kid/class'
    | '/kid/home'
    | '/kid/me'
    | '/kid/practice'
    | '/kid/ready'
    | '/kid/tracks'
    | '/kid/treasures'
    | '/kid/welcome'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/kid/chapter/$chapterId'
    | '/kid/checkpoint/$checkpointId'
    | '/kid/lesson/$lessonId'
    | '/kid/module/$moduleId'
    | '/kid/reward/$rewardId'
    | '/kid/setup/guide'
    | '/kid/setup/name'
    | '/kid/setup/theme'
    | '/kid/module/$moduleId/result'
    | '/kid/module/$moduleId/review'
    | '/kid/module/$moduleId/test'
    | '/kid/track/$trackId/map'
  id:
    | '__root__'
    | '/'
    | '/adult/consent'
    | '/adult/dashboard'
    | '/adult/recover'
    | '/adult/sign-in'
    | '/kid/class'
    | '/kid/home'
    | '/kid/me'
    | '/kid/practice'
    | '/kid/ready'
    | '/kid/tracks'
    | '/kid/treasures'
    | '/kid/welcome'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/kid/chapter/$chapterId'
    | '/kid/checkpoint/$checkpointId'
    | '/kid/lesson/$lessonId'
    | '/kid/module/$moduleId'
    | '/kid/reward/$rewardId'
    | '/kid/setup/guide'
    | '/kid/setup/name'
    | '/kid/setup/theme'
    | '/kid/module/$moduleId/result'
    | '/kid/module/$moduleId/review'
    | '/kid/module/$moduleId/test'
    | '/kid/track/$trackId/map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdultConsentRoute: typeof AdultConsentRoute
  AdultDashboardRoute: typeof AdultDashboardRoute
  AdultRecoverRoute: typeof AdultRecoverRoute
  AdultSignInRoute: typeof AdultSignInRoute
  KidClassRoute: typeof KidClassRoute
  KidHomeRoute: typeof KidHomeRoute
  KidMeRoute: typeof KidMeRoute
  KidPracticeRoute: typeof KidPracticeRoute
  KidReadyRoute: typeof KidReadyRoute
  KidTracksRoute: typeof KidTracksRoute
  KidTreasuresRoute: typeof KidTreasuresRoute
  KidWelcomeRoute: typeof KidWelcomeRoute
  Char91__componentChar93PreviewSplatRoute: typeof Char91__componentChar93PreviewSplatRoute
  Char91__mockupChar93PreviewSplatRoute: typeof Char91__mockupChar93PreviewSplatRoute
  KidChapterChapterIdRoute: typeof KidChapterChapterIdRoute
  KidCheckpointCheckpointIdRoute: typeof KidCheckpointCheckpointIdRoute
  KidLessonLessonIdRoute: typeof KidLessonLessonIdRoute
  KidModuleModuleIdRoute: typeof KidModuleModuleIdRouteWithChildren
  KidRewardRewardIdRoute: typeof KidRewardRewardIdRoute
  KidSetupGuideRoute: typeof KidSetupGuideRoute
  KidSetupNameRoute: typeof KidSetupNameRoute
  KidSetupThemeRoute: typeof KidSetupThemeRoute
  KidTrackTrackIdMapRoute: typeof KidTrackTrackIdMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/welcome': {
      id: '/kid/welcome'
      path: '/kid/welcome'
      fullPath: '/kid/welcome'
      preLoaderRoute: typeof KidWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/treasures': {
      id: '/kid/treasures'
      path: '/kid/treasures'
      fullPath: '/kid/treasures'
      preLoaderRoute: typeof KidTreasuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/tracks': {
      id: '/kid/tracks'
      path: '/kid/tracks'
      fullPath: '/kid/tracks'
      preLoaderRoute: typeof KidTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/ready': {
      id: '/kid/ready'
      path: '/kid/ready'
      fullPath: '/kid/ready'
      preLoaderRoute: typeof KidReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/practice': {
      id: '/kid/practice'
      path: '/kid/practice'
      fullPath: '/kid/practice'
      preLoaderRoute: typeof KidPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/me': {
      id: '/kid/me'
      path: '/kid/me'
      fullPath: '/kid/me'
      preLoaderRoute: typeof KidMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/home': {
      id: '/kid/home'
      path: '/kid/home'
      fullPath: '/kid/home'
      preLoaderRoute: typeof KidHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/class': {
      id: '/kid/class'
      path: '/kid/class'
      fullPath: '/kid/class'
      preLoaderRoute: typeof KidClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adult/sign-in': {
      id: '/adult/sign-in'
      path: '/adult/sign-in'
      fullPath: '/adult/sign-in'
      preLoaderRoute: typeof AdultSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adult/recover': {
      id: '/adult/recover'
      path: '/adult/recover'
      fullPath: '/adult/recover'
      preLoaderRoute: typeof AdultRecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adult/dashboard': {
      id: '/adult/dashboard'
      path: '/adult/dashboard'
      fullPath: '/adult/dashboard'
      preLoaderRoute: typeof AdultDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adult/consent': {
      id: '/adult/consent'
      path: '/adult/consent'
      fullPath: '/adult/consent'
      preLoaderRoute: typeof AdultConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/setup/theme': {
      id: '/kid/setup/theme'
      path: '/kid/setup/theme'
      fullPath: '/kid/setup/theme'
      preLoaderRoute: typeof KidSetupThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/setup/name': {
      id: '/kid/setup/name'
      path: '/kid/setup/name'
      fullPath: '/kid/setup/name'
      preLoaderRoute: typeof KidSetupNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/setup/guide': {
      id: '/kid/setup/guide'
      path: '/kid/setup/guide'
      fullPath: '/kid/setup/guide'
      preLoaderRoute: typeof KidSetupGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/reward/$rewardId': {
      id: '/kid/reward/$rewardId'
      path: '/kid/reward/$rewardId'
      fullPath: '/kid/reward/$rewardId'
      preLoaderRoute: typeof KidRewardRewardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/module/$moduleId': {
      id: '/kid/module/$moduleId'
      path: '/kid/module/$moduleId'
      fullPath: '/kid/module/$moduleId'
      preLoaderRoute: typeof KidModuleModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/lesson/$lessonId': {
      id: '/kid/lesson/$lessonId'
      path: '/kid/lesson/$lessonId'
      fullPath: '/kid/lesson/$lessonId'
      preLoaderRoute: typeof KidLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/checkpoint/$checkpointId': {
      id: '/kid/checkpoint/$checkpointId'
      path: '/kid/checkpoint/$checkpointId'
      fullPath: '/kid/checkpoint/$checkpointId'
      preLoaderRoute: typeof KidCheckpointCheckpointIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/chapter/$chapterId': {
      id: '/kid/chapter/$chapterId'
      path: '/kid/chapter/$chapterId'
      fullPath: '/kid/chapter/$chapterId'
      preLoaderRoute: typeof KidChapterChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__mockup/preview/$': {
      id: '/__mockup/preview/$'
      path: '/__mockup/preview/$'
      fullPath: '/__mockup/preview/$'
      preLoaderRoute: typeof Char91__mockupChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__component/preview/$': {
      id: '/__component/preview/$'
      path: '/__component/preview/$'
      fullPath: '/__component/preview/$'
      preLoaderRoute: typeof Char91__componentChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/track/$trackId/map': {
      id: '/kid/track/$trackId/map'
      path: '/kid/track/$trackId/map'
      fullPath: '/kid/track/$trackId/map'
      preLoaderRoute: typeof KidTrackTrackIdMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid/module/$moduleId/test': {
      id: '/kid/module/$moduleId/test'
      path: '/test'
      fullPath: '/kid/module/$moduleId/test'
      preLoaderRoute: typeof KidModuleModuleIdTestRouteImport
      parentRoute: typeof KidModuleModuleIdRoute
    }
    '/kid/module/$moduleId/review': {
      id: '/kid/module/$moduleId/review'
      path: '/review'
      fullPath: '/kid/module/$moduleId/review'
      preLoaderRoute: typeof KidModuleModuleIdReviewRouteImport
      parentRoute: typeof KidModuleModuleIdRoute
    }
    '/kid/module/$moduleId/result': {
      id: '/kid/module/$moduleId/result'
      path: '/result'
      fullPath: '/kid/module/$moduleId/result'
      preLoaderRoute: typeof KidModuleModuleIdResultRouteImport
      parentRoute: typeof KidModuleModuleIdRoute
    }
  }
}

interface KidModuleModuleIdRouteChildren {
  KidModuleModuleIdResultRoute: typeof KidModuleModuleIdResultRoute
  KidModuleModuleIdReviewRoute: typeof KidModuleModuleIdReviewRoute
  KidModuleModuleIdTestRoute: typeof KidModuleModuleIdTestRoute
}

const KidModuleModuleIdRouteChildren: KidModuleModuleIdRouteChildren = {
  KidModuleModuleIdResultRoute: KidModuleModuleIdResultRoute,
  KidModuleModuleIdReviewRoute: KidModuleModuleIdReviewRoute,
  KidModuleModuleIdTestRoute: KidModuleModuleIdTestRoute,
}

const KidModuleModuleIdRouteWithChildren =
  KidModuleModuleIdRoute._addFileChildren(KidModuleModuleIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdultConsentRoute: AdultConsentRoute,
  AdultDashboardRoute: AdultDashboardRoute,
  AdultRecoverRoute: AdultRecoverRoute,
  AdultSignInRoute: AdultSignInRoute,
  KidClassRoute: KidClassRoute,
  KidHomeRoute: KidHomeRoute,
  KidMeRoute: KidMeRoute,
  KidPracticeRoute: KidPracticeRoute,
  KidReadyRoute: KidReadyRoute,
  KidTracksRoute: KidTracksRoute,
  KidTreasuresRoute: KidTreasuresRoute,
  KidWelcomeRoute: KidWelcomeRoute,
  Char91__componentChar93PreviewSplatRoute:
    Char91__componentChar93PreviewSplatRoute,
  Char91__mockupChar93PreviewSplatRoute: Char91__mockupChar93PreviewSplatRoute,
  KidChapterChapterIdRoute: KidChapterChapterIdRoute,
  KidCheckpointCheckpointIdRoute: KidCheckpointCheckpointIdRoute,
  KidLessonLessonIdRoute: KidLessonLessonIdRoute,
  KidModuleModuleIdRoute: KidModuleModuleIdRouteWithChildren,
  KidRewardRewardIdRoute: KidRewardRewardIdRoute,
  KidSetupGuideRoute: KidSetupGuideRoute,
  KidSetupNameRoute: KidSetupNameRoute,
  KidSetupThemeRoute: KidSetupThemeRoute,
  KidTrackTrackIdMapRoute: KidTrackTrackIdMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
